from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NotepadWindow(object):
    def setupUi(self, NotepadWindow):
        NotepadWindow.setObjectName("NotepadWindow")
        NotepadWindow.resize(622, 493)
        self.centralwidget = QtWidgets.QWidget(NotepadWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_3.addWidget(self.listWidget)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEditor = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.textEditor.setFont(font)
        self.textEditor.setObjectName("textEditor")
        self.verticalLayout.addWidget(self.textEditor)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.verticalLayout.addLayout(self.buttonLayout)
        self.horizontalLayout.addLayout(self.verticalLayout)
        NotepadWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(NotepadWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 622, 33))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        NotepadWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(NotepadWindow)
        self.statusbar.setObjectName("statusbar")
        NotepadWindow.setStatusBar(self.statusbar)
        self.actionBaru = QtWidgets.QAction(NotepadWindow)
        self.actionBaru.setObjectName("actionBaru")
        self.actionSimpanFile = QtWidgets.QAction(NotepadWindow)
        self.actionSimpanFile.setObjectName("actionSimpanFile")
        self.actionBukaFile = QtWidgets.QAction(NotepadWindow)
        self.actionBukaFile.setObjectName("actionBukaFile")
        self.actionKeluar = QtWidgets.QAction(NotepadWindow)
        self.actionKeluar.setObjectName("actionKeluar")
        self.actionUndo = QtWidgets.QAction(NotepadWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(NotepadWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.menuFile.addAction(self.actionBaru)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionBukaFile)
        self.menuFile.addAction(self.actionSimpanFile)
        self.menuFile.addAction(self.actionKeluar)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(NotepadWindow)
        QtCore.QMetaObject.connectSlotsByName(NotepadWindow)

    def retranslateUi(self, NotepadWindow):
        _translate = QtCore.QCoreApplication.translate
        NotepadWindow.setWindowTitle(_translate("NotepadWindow", "Notepad - Aplikasi Catatan"))
        self.pushButton.setText(_translate("NotepadWindow", "Daftar Catatan"))
        self.textEditor.setPlaceholderText(_translate("NotepadWindow", "Mulai ketik catatan Anda di sini..."))
        self.menuFile.setTitle(_translate("NotepadWindow", "File"))
        self.menuEdit.setTitle(_translate("NotepadWindow", "Edit"))
        self.actionBaru.setText(_translate("NotepadWindow", "Baru"))
        self.actionBukaFile.setText(_translate("NotepadWindow", "Buka File"))
        self.actionSimpanFile.setText(_translate("NotepadWindow", "Simpan ke File"))
        self.actionKeluar.setText(_translate("NotepadWindow", "Keluar"))
        self.actionUndo.setText(_translate("NotepadWindow", "Undo"))
        self.actionRedo.setText(_translate("NotepadWindow", "Redo"))
